require "rspec/core/rake_task"

desc "Run integration specs"
RSpec::Core::RakeTask.new('spec:integration') do |t|
  t.pattern = 'spec/integration/*_spec.rb'
end


desc "Run integration spkie"
RSpec::Core::RakeTask.new('spec:spike') do |t|
  t.pattern = 'spec/integration/dictionary_spec.rb'
end